spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5532/test?currentSchema=bankinc
    username: postgres
    password: juang
    driverClassName: org.postgresql.Driver
  application:
    name: bankinc    
  sql:
    init:
      mode: always

      