spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/test?currentSchema=bankinc
    username: postgres
    password: juang
    driverClassName: org.postgresql.Driver
  application:
    name: bankinc    
  
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
